on:
  schedule:
    - cron: "30 12 * * *"

jobs:
  build:
    name: Render chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install requirements
        run: |
          python -m pip install -r requirements.txt
      - name: Render chart
        run: python chart.py
        env:
          GITHUB_PAT: ${{ secrets.PAT_GITHUB }} # GitHub refuses to let me add a secret called GITHUB_PAT or GITHUB_PERSONAL_ACCESS_TOKEN, so I'm reversing the name
      - name: Commit changes
        run: |
          git config --local user.email "actions@rileyflynn.me"
          git config --local user.name "GitHub Action"
          git add languages.svg
          git commit -m "Update languages breakdown" || echo "No changes to commit"
          git push origin master || echo "No changes to commit"
