on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Render chart
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Set up uv
        # Install latest uv version using the installer
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install requirements
        run: |
          uv sync --all-extras
      - name: Render chart
        run: uv run chart.py
        env:
          GITHUB_PAT: ${{ secrets.PAT_GITHUB }} # GitHub refuses to let me add a secret called GITHUB_PAT or GITHUB_PERSONAL_ACCESS_TOKEN, so I'm reversing the name
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Update chart"
          commit_author: "Chartbot <chartbot@bootleg.technology>"
          commit_user_email: "chartbot@bootleg.technology"
